In [3]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv("matchwise_events_data_updated.csv")
df1 = pd.read_csv("season_matchwise_data.csv")

/var/folders/l7/dwz00nyj4vz8vc2_np2c6x280000gn/T/ipykernel_24690/3971650708.py:1: DtypeWarning: Columns (18,41,75,76,85,88,95,96,97,99,100,101,102,107,108,109,110,111,112,114,115,116,117,119,120,121,122,123,124,125,126,127,129,130,131,132,133,134,135,136,137,138,139) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("matchwise_events_data_updated.csv")

In [4]:
df.head()

,match_id,id,index,period,timestamp,minute,second,possession,duration,type.id,...,shot.saved_off_target,goalkeeper.shot_saved_off_target,dribble.no_touch,goalkeeper.success_in_play,goalkeeper.lost_in_play,jersey_number,started,subID,minMinute,minsPlayed
0,303421,99d03ac6-bd7b-452a-91be-32e28f96bc1c,1,1,00:00.0,0,0,1,0.000000,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,303421,45e9a850-9a07-4266-8c05-66565e7ac83c,2,1,00:00.0,0,0,1,0.000000,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,303421,715a7900-5e3a-41f6-9870-44dc657ba2bc,3,1,00:00.0,0,0,1,0.000000,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,303421,9df4334c-c6e4-4457-97f2-8948375695c7,4,1,00:00.0,0,0,1,0.000000,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,303421,1a45cc07-8721-46a1-81eb-ac83d3e44b6d,5,1,00:00.6,0,0,2,1.235451,30,...,NaN,NaN,NaN,NaN,NaN,9.0,Yes,NaN,0.0,92.0

In [22]:
df1.head()

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,competition_stage.id,competition_stage.name,stadium.id,stadium.name,stadium.country.id,stadium.country.name,referee.id,referee.name,referee.country.id,referee.country.name
0,303421,7/19/2020,00:00.0,0,5,available,unscheduled,2020-07-29T05:00,NaN,38,...,1,Regular Season,348.0,Estadio de Mendizorroza,214.0,Spain,207.0,J. Martínez,214.0,Spain
1,303493,6/23/2020,00:00.0,1,0,available,unscheduled,2020-07-29T05:00,NaN,31,...,1,Regular Season,342.0,Camp Nou,214.0,Spain,183.0,Jesús Gil,214.0,Spain
2,303516,6/27/2020,00:00.0,2,2,available,unscheduled,2020-07-29T05:00,NaN,32,...,1,Regular Season,653.0,Abanca-Balaídos,214.0,Spain,451.0,G. Cuadra,214.0,Spain
3,303680,7/11/2020,30:00.0,0,1,available,unscheduled,2020-12-18T12:10:38.985394,NaN,36,...,1,Regular Season,622.0,Estadio Municipal José Zorrilla,214.0,Spain,180.0,Antonio Mateu,214.0,Spain
4,303532,6/16/2020,00:00.0,2,0,available,unscheduled,2020-07-29T05:00,NaN,29,...,1,Regular Season,342.0,Camp Nou,214.0,Spain,207.0,J. Martínez,214.0,Spain

In [26]:
df = pd.merge(df, df1, on="match_id", how="left")

In [36]:
for i in df1.columns:
    print(i)

match_id
match_date
kick_off
home_score
away_score
match_status
match_status_360
last_updated
last_updated_360
match_week
competition.competition_id
competition.country_name
competition.competition_name
season.season_id
season.season_name
home_team.home_team_id
home_team.home_team_name
home_team.home_team_gender
home_team.home_team_group
home_team.country.id
home_team.country.name
home_team.managers
away_team.away_team_id
away_team.away_team_name
away_team.away_team_gender
away_team.away_team_group
away_team.country.id
away_team.country.name
away_team.managers
metadata.data_version
metadata.shot_fidelity_version
metadata.xy_fidelity_version
competition_stage.id
competition_stage.name
stadium.id
stadium.name
stadium.country.id
stadium.country.name
referee.id
referee.name
referee.country.id
referee.country.name

In [9]:
for i in df.columns:
    print(i)

match_id
id
index
period
timestamp
minute
second
possession
duration
type.id
type.name
possession_team.id
possession_team.name
play_pattern.id
play_pattern.name
team.id
team.name
tactics.formation
tactics.lineup
related_events
off_camera
location
player.id
player.name
position.id
position.name
pass.recipient.id
pass.recipient.name
pass.length
pass.angle
pass.height.id
pass.height.name
pass.end_location
pass.body_part.id
pass.body_part.name
pass.type.id
pass.type.name
carry.end_location
under_pressure
dribble.outcome.id
dribble.outcome.name
dribble.nutmeg
duel.type.id
duel.type.name
duel.outcome.id
duel.outcome.name
pass.outcome.id
pass.outcome.name
ball_receipt.outcome.id
ball_receipt.outcome.name
counterpress
ball_recovery.recovery_failure
pass.assisted_shot_id
pass.shot_assist
shot.statsbomb_xg
shot.end_location
shot.key_pass_id
shot.technique.id
shot.technique.name
shot.body_part.id
shot.body_part.name
shot.type.id
shot.type.name
shot.outcome.id
shot.outcome.name
shot.freeze_frame
goalkeeper.end_location
goalkeeper.position.id
goalkeeper.position.name
goalkeeper.type.id
goalkeeper.type.name
clearance.head
clearance.body_part.id
clearance.body_part.name
pass.aerial_won
pass.deflected
block.deflection
pass.switch
clearance.right_foot
foul_won.defensive
interception.outcome.id
interception.outcome.name
pass.cross
shot.first_time
out
pass.through_ball
pass.technique.id
pass.technique.name
shot.one_on_one
goalkeeper.body_part.id
goalkeeper.body_part.name
goalkeeper.outcome.id
goalkeeper.outcome.name
goalkeeper.technique.id
goalkeeper.technique.name
pass.goal_assist
pass.no_touch
foul_committed.offensive
foul_committed.type.id
foul_committed.type.name
dribble.overrun
ball_recovery.offensive
pass.outswinging
substitution.outcome.id
substitution.outcome.name
substitution.replacement.id
substitution.replacement.name
clearance.left_foot
foul_committed.advantage
foul_won.advantage
injury_stoppage.in_chain
block.offensive
shot.redirect
50_50.outcome.id
50_50.outcome.name
shot.aerial_won
pass.cut_back
miscontrol.aerial_won
foul_committed.card.id
foul_committed.card.name
pass.inswinging
clearance.aerial_won
clearance.other
shot.open_goal
pass.straight
shot.saved_to_post
goalkeeper.shot_saved_to_post
pass.miscommunication
bad_behaviour.card.id
bad_behaviour.card.name
shot.deflected
block.save_block
foul_committed.penalty
foul_won.penalty
goalkeeper.punched_out
shot.saved_off_target
goalkeeper.shot_saved_off_target
dribble.no_touch
goalkeeper.success_in_play
goalkeeper.lost_in_play
jersey_number
started
subID
minMinute
minsPlayed

In [27]:
df["pass.outcome.id"] = np.where(df["pass.outcome.id"].isnull(), 1,
                                         df["pass.outcome.id"])
df["pass.outcome.name"] = np.where(df["pass.outcome.name"].isnull(), "Complete",
                                            df["pass.outcome.name"])

In [28]:
booleanCols = ["under_pressure", "pass.shot_assist", "pass.aerial_won",
               "pass.deflected", "pass.switch", "pass.cross", "pass.through_ball",
               "pass.goal_assist", "pass.no_touch", "pass.outswinging",
               "pass.cut_back", "pass.inswinging", "pass.straight", "pass.miscommunication"]

unwantedCols = ["player.name", "pass.recipient.name",
                "pass.end_location", "location",
                "pass.assisted_shot_id", "id", "timestamp",
                "position.name", "possession_team.name",
                "team.name", "type.name"]

catPassCols = df.select_dtypes(include="object").columns
catPassCols = catPassCols.symmetric_difference(unwantedCols)
df[catPassCols] = df[catPassCols].astype("category")

for col in booleanCols:
    try:
        df[col] = df[col].cat.add_categories(False)
    except ValueError:
        print(sys.exc_info())
        
    df[col] = df[col].fillna(False)

In [29]:
#attacker player position.ids are >16

In [30]:
# End location for carry:
df["endXCarry"] = df["carry.end_location"]\
    .str.split(", ", expand=True)[0].str[1:].apply(pd.to_numeric)
df["endYCarry"] = df["carry.end_location"]\
    .str.split(", ", expand=True)[1].str[:-1].apply(pd.to_numeric)

# End location for shots:
df["endXShot"] = df["shot.end_location"]\
    .str.split(", ", expand=True)[0].str[1:].apply(pd.to_numeric)
df["endYShot"] = df["shot.end_location"]\
    .str.split(", ", expand=True)[1].str.replace("]", "").apply(pd.to_numeric)
df["goalHeight"] = df["shot.end_location"]\
    .str.split(", ", expand=True)[2].str[:-1].apply(pd.to_numeric)


df["startX"] = df["location"].str.split(", ",expand=True)[0].str[1:].apply(pd.to_numeric)
df["startY"] = df["location"].str.split(", ",expand=True)[1].str[:-1].apply(pd.to_numeric)

df["endX"] = df["pass.end_location"].str.split(", ",expand=True)[0].str[1:].apply(pd.to_numeric)
df["endY"] = df["pass.end_location"].str.split(", ",expand=True)[1].str[:-1].apply(pd.to_numeric)

/var/folders/l7/dwz00nyj4vz8vc2_np2c6x280000gn/T/ipykernel_24690/3873736025.py:10: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df["endYShot"] = df["shot.end_location"]\

In [16]:
df.head()

,match_id,id,index,period,timestamp,minute,second,possession,duration,type.id,...,minsPlayed,endXCarry,endYCarry,endXShot,endYShot,goalHeight,startX,startY,endX,endY
0,303421,99d03ac6-bd7b-452a-91be-32e28f96bc1c,1,1,00:00.0,0,0,1,0.000000,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,303421,45e9a850-9a07-4266-8c05-66565e7ac83c,2,1,00:00.0,0,0,1,0.000000,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,303421,715a7900-5e3a-41f6-9870-44dc657ba2bc,3,1,00:00.0,0,0,1,0.000000,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,303421,9df4334c-c6e4-4457-97f2-8948375695c7,4,1,00:00.0,0,0,1,0.000000,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,303421,1a45cc07-8721-46a1-81eb-ac83d3e44b6d,5,1,00:00.6,0,0,2,1.235451,30,...,92.0,NaN,NaN,NaN,NaN,NaN,60.0,40.0,43.2,40.7

In [32]:
df.to_csv("all_data_for_tab.csv")

In [4]:
df = pd.read_csv("all_data_for_tab.csv")

/var/folders/l7/dwz00nyj4vz8vc2_np2c6x280000gn/T/ipykernel_75486/2873079538.py:1: DtypeWarning: Columns (19,42,77,89,98,100,101,102,108,109,110,111,112,113,115,116,118,120,122,123,124,126,127,130,131,132,133,134,135,136,137,138,139,140) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("all_data_for_tab.csv")

In [37]:
el_classico = df[df["match_id"]==303470]

In [35]:
el_classico.to_csv("all_elclassico.csv")

In [153]:
el_classico[["type.id","type.name"]].value_counts()

type.id  type.name
30       Pass               1220
42       Ball Receipt*      1182
43       Carry               998
17       Pressure            392
2        Ball Recovery        80
4        Duel                 47
10       Interception         34
6        Block                33
22       Foul Committed       32
21       Foul Won             30
14       Dribble              29
23       Goal Keeper          26
3        Dispossessed         24
16       Shot                 22
9        Clearance            21
38       Miscontrol           19
39       Dribbled Past        17
19       Substitution          6
18       Half Start            4
34       Half End              4
35       Starting XI           2
40       Injury Stoppage       2
24       Bad Behaviour         2
36       Tactical Shift        1
dtype: int64

In [165]:
el_classico[["shot.outcome.id","shot.outcome.name"]].value_counts()

shot.outcome.id  shot.outcome.name
98.0             Off T                8
100.0            Saved                6
96.0             Blocked              5
97.0             Goal                 2
101.0            Wayward              1
dtype: int64

In [154]:
el_classico[el_classico["type.id"]==30].shape #total passes

(1220, 196)

In [155]:
el_classico[el_classico["type.id"]==16].shape #shots attempted

(22, 196)

In [163]:
el_classico[el_classico["type.id"].isin([4,10,6])].shape #defensive actions

(114, 196)

In [166]:
el_classico[el_classico["shot.outcome.id"]==100].shape #saves made by keeper

(6, 196)

In [167]:
el_classico[el_classico["type.id"]==22].shape #fouls commited

(32, 196)

In [9]:
df.head()

,Unnamed: 0,match_id,id,index,period,timestamp,minute,second,possession,duration,...,referee.country.name,endXCarry,endYCarry,endXShot,endYShot,goalHeight,startX,startY,endX,endY
0,0,303421,99d03ac6-bd7b-452a-91be-32e28f96bc1c,1,1,00:00.0,0,0,1,0.000000,...,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,303421,45e9a850-9a07-4266-8c05-66565e7ac83c,2,1,00:00.0,0,0,1,0.000000,...,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,303421,715a7900-5e3a-41f6-9870-44dc657ba2bc,3,1,00:00.0,0,0,1,0.000000,...,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,303421,9df4334c-c6e4-4457-97f2-8948375695c7,4,1,00:00.0,0,0,1,0.000000,...,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,303421,1a45cc07-8721-46a1-81eb-ac83d3e44b6d,5,1,00:00.6,0,0,2,1.235451,...,Spain,NaN,NaN,NaN,NaN,NaN,60.0,40.0,43.2,40.7

In [13]:
df.groupby(['match_id',"possession"])['player.name'].apply(list)

match_id  possession
303377    1                                          [nan, nan, nan, nan]
          2             [Antoine Griezmann, Sergio Busquets i Burgos, ...
          3             [Xabier Etxeita Gorritxategi, Allan Romeo Nyom...
          4             [Allan Romeo Nyom, Oghenekaro Etebo, Oghenekar...
          5             [Samuel Yves Umtiti, Sergio Busquets i Burgos,...
                                              ...
303731    180           [Samuel Yves Umtiti, Samuel Yves Umtiti, Samue...
          181           [Enrique González Casín, Anaitz Arbilla Zabala...
          182           [Samuel Yves Umtiti, Frenkie de Jong, Frenkie ...
          183           [Enrique González Casín, Esteban Rodrigo Burgo...
          184           [Frenkie de Jong, Frenkie de Jong, Pablo Ezequ...
Name: player.name, Length: 5834, dtype: object

In [14]:
xgChainData = df.groupby(['match_id',"possession"])['player.name'].apply(list)

In [17]:
df.groupby(['match_id','possession'])['shot.statsbomb_xg'].sum()

match_id  possession
303377    1             0.000000
          2             0.000000
          3             0.000000
          4             0.000000
          5             0.000000
                          ...
303731    180           0.835386
          181           0.000000
          182           1.269341
          183           0.000000
          184           0.000000
Name: shot.statsbomb_xg, Length: 5834, dtype: float64

In [18]:
df.groupby(["match_id", "possession"]).agg({
    "shot.outcome.id": lambda x: (x == 97).sum()})

                     shot.outcome.id
match_id possession
303377   1                         0
         2                         0
         3                         0
         4                         0
         5                         0
...                              ...
303731   180                       1
         181                       0
         182                       1
         183                       0
         184                       0

[5834 rows x 1 columns]

In [19]:
xgData = df.groupby(['match_id','possession'])['shot.statsbomb_xg'].sum()

In [21]:
goalData = df.groupby(["match_id", "possession"]).agg({
    "shot.outcome.id": lambda x: (x == 97).sum()})

In [119]:
pd.concat([xgChainData,xgData,goalData],axis=1)

                                                           player.name  \
match_id possession
303377   1                                        [nan, nan, nan, nan]
         2           [Antoine Griezmann, Sergio Busquets i Burgos, ...
         3           [Xabier Etxeita Gorritxategi, Allan Romeo Nyom...
         4           [Allan Romeo Nyom, Oghenekaro Etebo, Oghenekar...
         5           [Samuel Yves Umtiti, Sergio Busquets i Burgos,...
...                                                                ...
303731   180         [Samuel Yves Umtiti, Samuel Yves Umtiti, Samue...
         181         [Enrique González Casín, Anaitz Arbilla Zabala...
         182         [Samuel Yves Umtiti, Frenkie de Jong, Frenkie ...
         183         [Enrique González Casín, Esteban Rodrigo Burgo...
         184         [Frenkie de Jong, Frenkie de Jong, Pablo Ezequ...

                     shot.statsbomb_xg  shot.outcome.id
match_id possession
303377   1                    0.000000                0
         2                    0.000000                0
         3                    0.000000                0
         4                    0.000000                0
         5                    0.000000                0
...                                ...              ...
303731   180                  0.835386                1
         181                  0.000000                0
         182                  1.269341                1
         183                  0.000000                0
         184                  0.000000                0

[5834 rows x 3 columns]

In [122]:
xgChainFinal = pd.concat([xgChainData,xgData,goalData],axis=1)

In [123]:
xgChainFinal = xgChainFinal.reset_index()

In [118]:
from copy import deepcopy
xgChainFinal = deepcopy(xgChainFinal[xgChainFinal["shot.statsbomb_xg"]>0])

In [30]:
chainCond = xgChainFinal["player.name"].apply(lambda x: "Luis Alberto Suárez Díaz" in x)

In [35]:
xgChainFinal.loc[chainCond,"shot.statsbomb_xg"].shape[0]

191

In [28]:
playerNames = df["player.name"].unique()
for player in playerNames:
    chainCond = xgChainFinal["player.name"].apply(lambda x: player in x)
    print(player, xgChainFinal.loc[chainCond, "shot.statsbomb_xg"].shape[0],
          xgChainFinal.loc[chainCond, "shot.statsbomb_xg"].sum().round(1), "\n")
#player name ; number pf involvements which lead to shot; expected goals from build up

nan 26 3.3

Luis Alberto Suárez Díaz 191 26.1

Sergio Busquets i Burgos 258 33.8

Clément Lenglet 195 27.8

Ricard Puig Martí 72 9.2

Ronald Federico Araújo da Silva 22 3.1

Jordi Alba Ramos 175 24.1

Arturo Erasmo Vidal Pardo 195 24.8

Oliver Burke 4 0.6

Sergi Roberto Carnicer 194 23.5

Lionel Andrés Messi Cuccittini 378 53.2

Manuel Alejandro García Sánchez 17 2.4

José Luis Sanmartín Mato 6 0.4

Lucas Pérez Martínez 5 0.4

Norberto Murara Neto 17 1.4

Anssumane Fati 89 12.5

Víctor Camarasa Ferrando 8 0.8

Edgar Antonio Méndez Ortega 4 0.2

Martín Aguirregabiria Padilla 9 0.8

Víctor Laguardia Cisneros 6 0.9

Roberto Jiménez Gago 17 3.1

Adrián Marín Gómez 9 1.4

Lisandro Magallán 3 0.6

Luis Jesús Rioja González 5 0.5

Pere Pons Riera 4 0.5

Alberto Rodríguez Baró 1 0.1

Nélson Cabral Semedo 161 20.3

Ljubomir Fejsa 3 0.3

Frenkie de Jong 150 21.3

Abdallahi Mohamed Mahmoud 1 0.1

Martin Braithwaite Christensen 47 7.8

Oihan Sancet Tirapu 7 1.1

Yeray Álvarez López 9 1.5

Íñigo Lekue Martínez 4 0.7

Iñigo Córdoba Kerejeta 7 0.7

Antoine Griezmann 196 28.0

Arthur Henrique Ramos de Oliveira Melo 95 16.2

Gerard Piqué Bernabéu 277 36.5

Unai López Cabrera 6 0.7

Unai Simón Mendibil 17 2.0

Mikel Vesga Arruti 10 1.4

Unai Núñez Gestoso 9 1.2

Iñaki Williams Arthuer 5 0.7

Óscar de Marcos Arana 7 0.7

Mikel Balenziaga Oruesagasti 7 1.3

Marc-André ter Stegen 351 43.8

Iker Muniain Goñi 3 0.5

Daniel García Carrillo 4 0.9

Ivan Rakitić 191 25.4

Asier Villalibre Molina 2 0.5

Ander Capa Rodríguez 4 0.6

Raúl García Escudero 3 0.5

Iago Aspas Juncal 19 3.0

Samuel Yves Umtiti 72 10.2

Denis Suárez Fernández 14 1.9

Jacobo González Rodrigañez 9 0.7

Jorge Sáenz de Miera Colmeiro 9 0.5

Okay Yokuşlu 9 1.4

Fyodor Smolov 9 1.7

Brais Méndez Portela 7 0.8

Kevin Vázquez Comesaña 7 0.5

Joseph Aidoo 10 1.0

Néstor Alejandro Araújo Razo 10 0.9

Rubén Blanco Veiga 29 4.3

Manuel Agudo Durán 9 1.3

Rafael Alcântara do Nascimento 4 0.9

Filip Bradarić 3 0.1

Jeison Fabián Murillo Cerón 1 0.1

Héctor Junior Firpo Adames 73 11.2

Santiago Mina Lorenzo 1 0.8

Sergio Guardiola Navarro 15 1.0

Rubén Alcaraz Jiménez 5 0.2

Óscar Plano Pedreño 15 1.0

Enrique Pérez Muñoz 14 1.3

Joaquín Fernández Moreno 14 1.7

Jordi Masip López 27 4.2

Javier Moyano Lujano 9 0.5

Francisco José Olivas Alba 16 1.9

Federico San Emeterio Díaz 8 0.5

Raúl García Carnero 3 0.3

Javier Sánchez de Felipe 8 1.2

José Ignacio Martínez García 15 1.1

Pablo Hervías Ruiz 14 1.0

Enes Ünal 8 0.8

Sandro Ramírez Castillo 4 0.3

Waldo Rubio Martín 9 0.6

Miguel Ángel Guerrero Martín 3 1.3

Roque Mesa Quevedo 10 0.9

Javier Eraso Goñi 5 0.6

Chidozie Collins Awaziem 4 0.5

Aitor Ruibal García 6 0.2

Rubén Salvador Pérez Del Mármol 13 2.1

Jonathan Cristian Silva 7 1.6

José Luis García del Pozo 8 0.9

Iván Cuéllar Sacristán 25 3.4

Unai Bustinza Martínez 8 0.7

Rodrigo Tarín Higón 5 0.5

Roger Claver Assalé Djapone 5 0.3

Ibrahim Amadou 2 0.3

Guido Marcelo Carrillo 3 0.2

Kévin Manuel Rodrigues 4 0.5

Bryan Gil Salvatierra 1 0.3

Maximiliano Gómez González 7 1.3

Ferrán Torres García 8 1.2

Kevin Gameiro 6 0.4

Daniel Wass 8 1.5

Ezequiel Marcelo Garay 7 0.7

Gabriel Armando de Abreu 6 0.3

Francis Coquelin 7 0.6

Carlos Soler Barragán 6 0.6

Jaume Doménech Sánchez 13 1.1

Geoffrey Kondogbia 10 0.9

José Luis Gayá Peña 6 0.3

Rodrigo Moreno Machado 1 0.2

Jaume Vicent Costa Jordá 1 0.0

Álex Collado Gutiérrez 2 0.2

Rubén Sobrino Pozuelo 0 0.0

José Manuel Arnáiz Díaz 9 0.5

David García Zubiría 4 0.4

Raúl Rodríguez Navas 8 0.6

Aridane Hernández Umpiérrez 6 0.5

Adrián López Álvarez 5 0.2

Jon Moncayola Tollar 10 0.6

Pervis Josué Estupiñán Tenorio 8 0.5

Darko Brašanac 2 0.2

Iñigo Pérez Soto 7 0.7

Sergio Herrera Pirón 20 1.4

Ignacio Vidal Miralles 5 0.3

Oier Sanjurjo Mate 8 0.9

Enric Gallego Puigsech 0 0.0

Enrique Barja Afonso 3 0.5

Roberto Torres Morales 2 0.4

Antonio Latorre Grueso 2 0.4

Alexander Isak 17 2.2

Martin Ødegaard 18 1.8

Ander Barrenetxea Muguruza 7 0.5

Ignacio Monreal Eraso 17 1.9

Robin Aime Robert Le Normand 9 0.8

Alejandro Remiro Gargallo 30 5.0

Ander Guevara Lajo 22 3.1

Cristian Portugués Manzanera 10 0.5

Diego Javier Llorente Ríos 14 2.4

Mikel Merino Zazón 19 1.9

Andoni Gorosabel Espinosa 7 0.6

Mikel Oyarzabal Ugarte 17 3.1

Igor Zubeldía Elorza 16 3.0

Willian José da Silva 3 1.1

Raúl de Tomás Gómez 6 0.4

David López Silva 14 2.3

Pol Lozano Vizuete 0 0.0

Víctor Gómez Perea 9 0.7

Adrián Embarba Blázquez 6 0.6

Leandro Daniel Cabrera Sasía 6 1.1

Dídac Vilá Rosselló 14 1.6

Bernardo José Espinosa Zúñiga 9 1.0

Diego López Rodríguez 23 2.9

Marc Roca Junqué 15 1.3

Fernando Calero Villa 2 0.2

Víctor Sánchez Mata 0 0.0

Sergi Darder Moll 11 0.6

Víctor Campuzano Bonilla 3 0.1

Lei Wu 4 0.4

Diego da Silva Costa 7 0.5

José María Giménez de Vargas 4 0.2

Felipe Augusto de Almeida Monteiro 11 1.0

Renan Augusto Lodi dos Santos 11 0.6

Jan Oblak 24 2.1

Saúl Ñíguez Esclapez 21 2.5

Yannick Ferreira Carrasco 8 0.5

Marcos Llorente Moreno 5 0.3

Santiago Arias Naranjo 7 0.4

Thomas Teye Partey 17 0.9

Ángel Martín Correa 15 0.7

João Félix Sequeira 11 1.0

Álvaro Borja Morata Martín 15 0.9

Thomas Lemar 2 0.1

Víctor Machín Pérez 4 0.3

Joseba Zaldúa Bengoetxea 9 1.8

Adnan Januzaj 5 1.6

Carles Aleña Castillo 19 2.0

Karim Benzema 22 1.8

Carlos Henrique Casimiro 26 2.0

Toni Kroos 30 2.1

Francisco Román Alarcón Suárez 18 1.5

Sergio Ramos García 19 1.6

Raphaël Varane 17 1.5

Daniel Carvajal Ramos 24 2.3

Gareth Frank Bale 11 1.0

Federico Santiago Valverde Dipetta 16 1.3

Ferland Mendy 10 0.4

Thibaut Courtois 19 2.0

Luka Modrić 1 0.1

Rodrygo Silva de Goes 1 0.1

Stanislav Lobotka 3 0.5

Francisco José Beltrán Peinado 3 0.1

Lucas René Olaza Catrofe 7 0.5

David Juncà Reñé 5 0.4

Pione Sisto Ifolo Emirmija 5 0.4

Hugo Mallo Novegil 3 0.3

Pape Cheikh Diop Gueye 3 0.3

Ousmane Dembélé 30 4.1

Gabriel Matías Fernández Leites 0 0.0

Miguel Alfonso Herrero Javaloyas 13 1.6

Pedro Antonio Porro Sauceda 8 1.6

Federico Barba 8 1.3

Anuar Mohamed Tuhami 4 0.2

Mohamed Salisu Abdul Karim 6 1.3

Marc Pedraza Sarto 5 0.4

Takefusa Kubo 25 3.3

Joan Sastre Vanrell 21 2.5

Manuel Reina Rodríguez 34 5.6

Ante Budimir 13 2.2

Martin Valjent 22 4.2

Antonio José Raillo Arenas 17 3.6

Alejandro Pozo Pozo 12 1.8

Salvador Sevilla López 18 3.0

Daniel José Rodríguez Vázquez 29 3.3

Juan Camilo Hernández Suárez 11 0.9

Júnior Wakalibille Lago 3 0.2

Francisco Gámez López 16 2.8

Iddrisu Baba Mohammed 14 2.7

Yannis Salibur 3 0.3

Abdón Prats Bastidas 2 0.3

Luuk de Jong 12 1.6

Fernando Francisco Reges 21 1.9

Éver Maximiliano David Banega 21 2.0

Diego Carlos Santos Silva 11 1.1

Daniel Filipe Martins Carriço 7 0.7

Sergio Reguilón Rodríguez 18 1.4

Jean-Clair Todibo 6 1.2

Lucas Ariel Ocampos 20 2.0

Óliver Torres Muñoz 10 1.1

Jesús Navas González 14 1.5

Tomáš Vaclík 22 2.5

Munir El Haddadi Mohamed 9 1.1

Joan Jordán Moreno 11 1.4

Javier Hernández Balcázar 1 0.2

Ramon Olamilekan Azeez 10 1.7

Álvaro Vadillo Cifuentes 7 1.2

Carlos Fernández Luna 14 1.0

Dimitri Foulquier 9 1.0

Germán Sánchez Barahona 9 1.6

Rui Tiago Dantas da Silva 25 3.1

Darwin Daniel Machís Marcano 11 0.5

Yan Brice Eteki 8 0.6

Maxime Gonalons 10 0.7

Víctor David Díaz Miguel 15 1.8

Domingos Sousa Coutinho Meneses Duarte 15 2.3

Yangel Clemente Herrera Ravelo 10 1.1

José Antonio Rodríguez Díaz 13 2.0

José Antonio Martínez Gil 0 0.0

Carles Pérez Sayol 15 2.1

Jonathan Calleri 8 0.6

Javier López Rodríguez 7 0.7

Óscar Melendo Jiménez 3 0.2

Edinaldo Gomes Pereira 4 0.2

Matías Ezequiel Vargas Martín 5 0.7

Ander Iturraspe Derteano 2 0.1

Santiago Cazorla González 16 1.8

Pau Francisco Torres 13 1.0

Gerard Moreno Balaguero 14 1.6

Vicente Iborra De La Fuente 15 1.6

Rubén Peña Jiménez 7 0.3

André-Frank Zambo Anguissa 11 0.7

Xavier Quintillà Guasch 8 0.5

Javier Ontiveros Parra 8 0.5

Samuel Chimerenka Chukwueze 21 2.3

Raúl Albiol Tortajada 15 1.6

Sergio Asenjo Andrés 26 3.4

Karl Brillant Toko Ekambi 2 0.1

Moisés Gómez Bordonado 4 0.4

Carlos Arturo Bacca Ahumada 1 0.2

Jules Koundé 9 0.6

Jesús Joaquín Fernández Sáez de la Torre 3 0.5

Youssef En-Nesyri 14 1.2

Nemanja Gudelj 1 0.3

Franco Damián Vázquez 1 0.3

Marcelo Vieira da Silva Júnior 9 0.8

Vinícius José Paixão de Oliveira Júnior 7 0.6

Lucas Vázquez Iglesias 0 0.0

Mariano Díaz Mejía 1 0.1

Sergio Enrich Ametller 8 1.3

Pedro León Sánchez Gil 5 0.9

Fabián Ariel Orellana Valenzuela 18 2.4

Paulo André Rodrigues de Oliveira 6 1.6

Marko Dmitrović 20 6.5

Anaitz Arbilla Zabala 11 2.5

Sergio Álvarez Díaz 6 0.9

José Ángel Valdés Díaz 14 1.7

Pablo Ezequiel De Blasis 7 1.3

Charles Días Barbosa de Oliveira 6 0.4

Papa Kouly Diop 12 1.9

Eduardo Expósito Jaén 11 2.2

Takashi Inui 6 0.2

Enrique García Martínez 1 0.2

Borja Iglesias Quintas 1 0.1

William Silva de Carvalho 2 0.1

Marc Bartra Aregall 4 0.3

Sergio Canales Madrazo 3 1.2

Aïssa Mandi 1 0.0

Joel Robles Blázquez 10 1.5

Emerson Aparecido Leite de Souza Junior 4 0.1

Guido Rodríguez 7 0.6

Nabil Fekir 6 0.8

Alejandro Moreno Lopera 3 0.2

Lorenzo Jesús Morón García 2 0.1

Joaquín Sánchez Rodríguez 0 0.0

Cristian Tello Herrera 0 0.0

Roberto Soldado Rillo 5 1.0

Ángel Montoro Sánchez 4 0.4

Carlos Neva Tey 4 0.1

Alberto Moreno Pérez 10 1.7

Mario Gaspar Pérez Martínez 7 1.1

Francisco Alcácer García 3 0.8

Bruno Soriano Llido 2 0.3

Manuel Trigueros Muñoz 5 0.2

Fernando Niño Rodriguez 2 0.0

Enis Bardhi 8 1.0

Nemanja Radoja 7 1.8

Jorge Miramón Santagertrudis 11 3.2

José Ángel Gómez Campaña 22 2.2

Borja Mayoral Moya 10 2.0

Gonzalo Julián Melero Manzanares 13 2.8

Rúben Miguel Nunes Vezo 15 1.7

José Luis Morales Nogales 12 2.6

Carlos Clerc Martínez 5 0.3

Aitor Fernández Abarisketa 27 5.8

Sergio Postigo Redondo 18 3.0

Rubén Rochina Naixes 20 2.8

Nikola Vukčević 8 0.9

Erick Cathriel Cabaco Almada 0 0.0

Óscar Rodríguez Arnaiz 5 0.1

Dimitrios Siovas 1 0.0

Roberto José Rosales Altuve 5 0.2

Kenneth Josiah Omeruo 3 0.2

Moussa Wagué 6 0.5

Marc Cucurella Saseta 8 1.5

Jorge Molina Vidal 5 1.0

Djené Dakonam Ortega 5 0.5

Mauro Wilney Arambarri Rosa 10 1.6

Xabier Etxeita Gorritxategi 5 0.9

Nemanja Maksimović 10 1.4

Mathías Olivera Miramontes 3 0.4

Allan Romeo Nyom 4 0.7

Oghenekaro Etebo 3 0.4

Jaime Mata Arnaiz 11 2.1

David Soria Solís 12 1.9

Robert Kenedy Nunes do Nascimento 4 0.6

Ángel Luis Rodríguez Díaz 4 0.7

Amath Ndiaye 3 0.6

Héctor Miguel Herrera López 14 0.9

Jorge Resurrección Merodio 13 1.2

Mario Hermoso Canseco 11 0.9

Kieran Trippier 8 0.7

Aleix Febas Pérez 13 2.0

Josep Señé Escudero 4 0.4

Joaquín Navarro Jiménez 3 0.3

Rubén Duarte Sánchez 6 0.6

Javier Muñoz Jiménez 1 0.0

Mubarak Wakaso 4 0.2

Aleix Vidal Parreu 5 0.4

Fernando Pacheco Flores 8 1.3

Rodrigo Ely 2 0.3

Roger Martí Salvador 11 2.7

Antonio García Aranda 5 1.2

Hernâni Jorge Santos Fortes 5 0.7

Gonzalo Escalante 7 1.3

Álvaro Tejero Sacristán 10 2.0

Esteban Rodrigo Burgos 6 3.2

Enrique González Casín 1 0.8

Sebastián Carlos Cristóforo Pepe 0 0.0

In [124]:
dd = xgChainFinal

In [125]:
dd.head()

,match_id,possession,player.name,shot.statsbomb_xg,shot.outcome.id
0,303377,1,"[nan, nan, nan, nan]",0.0,0
1,303377,2,"[Antoine Griezmann, Sergio Busquets i Burgos, ...",0.0,0
2,303377,3,"[Xabier Etxeita Gorritxategi, Allan Romeo Nyom...",0.0,0
3,303377,4,"[Allan Romeo Nyom, Oghenekaro Etebo, Oghenekar...",0.0,0
4,303377,5,"[Samuel Yves Umtiti, Sergio Busquets i Burgos,...",0.0,0

In [137]:
teams = df["team.name"].unique()
teams_players = {}
for i in teams:
    teams_players[i] = []

In [143]:
for i in range(len(df)):
    player = df.loc[i]['player.name']
    team = df.loc[i]['team.name']
    if player not in teams_players[team]:
        teams_players[team].append(player)

In [144]:
teams_players

{'Deportivo Alavés': [nan,
  'Oliver Burke',
  'Manuel Alejandro García Sánchez',
  'José Luis Sanmartín Mato',
  'Lucas Pérez Martínez',
  'Víctor Camarasa Ferrando',
  'Edgar Antonio Méndez Ortega',
  'Martín Aguirregabiria Padilla',
  'Víctor Laguardia Cisneros',
  'Roberto Jiménez Gago',
  'Adrián Marín Gómez',
  'Lisandro Magallán',
  'Luis Jesús Rioja González',
  'Pere Pons Riera',
  'Alberto Rodríguez Baró',
  'Ljubomir Fejsa',
  'Abdallahi Mohamed Mahmoud',
  'Joaquín Navarro Jiménez',
  'Rubén Duarte Sánchez',
  'Javier Muñoz Jiménez',
  'Mubarak Wakaso',
  'Aleix Vidal Parreu',
  'Fernando Pacheco Flores',
  'Rodrigo Ely'],
 'Barcelona': [nan,
  'Luis Alberto Suárez Díaz',
  'Sergio Busquets i Burgos',
  'Clément Lenglet',
  'Ricard Puig Martí',
  'Ronald Federico Araújo da Silva',
  'Jordi Alba Ramos',
  'Arturo Erasmo Vidal Pardo',
  'Sergi Roberto Carnicer',
  'Lionel Andrés Messi Cuccittini',
  'Norberto Murara Neto',
  'Anssumane Fati',
  'Nélson Cabral Semedo',
  'Frenkie de Jong',
  'Martin Braithwaite Christensen',
  'Antoine Griezmann',
  'Arthur Henrique Ramos de Oliveira Melo',
  'Gerard Piqué Bernabéu',
  'Marc-André ter Stegen',
  'Ivan Rakitić',
  'Samuel Yves Umtiti',
  'Héctor Junior Firpo Adames',
  'Álex Collado Gutiérrez',
  'Carles Aleña Castillo',
  'Ousmane Dembélé',
  'Jean-Clair Todibo',
  'Carles Pérez Sayol',
  'Moussa Wagué'],
 'Athletic Bilbao': [nan,
  'Oihan Sancet Tirapu',
  'Yeray Álvarez López',
  'Íñigo Lekue Martínez',
  'Iñigo Córdoba Kerejeta',
  'Unai López Cabrera',
  'Unai Simón Mendibil',
  'Mikel Vesga Arruti',
  'Unai Núñez Gestoso',
  'Iñaki Williams Arthuer',
  'Óscar de Marcos Arana',
  'Mikel Balenziaga Oruesagasti',
  'Iker Muniain Goñi',
  'Daniel García Carrillo',
  'Asier Villalibre Molina',
  'Ander Capa Rodríguez',
  'Raúl García Escudero'],
 'Celta Vigo': [nan,
  'Iago Aspas Juncal',
  'Denis Suárez Fernández',
  'Jacobo González Rodrigañez',
  'Jorge Sáenz de Miera Colmeiro',
  'Okay Yokuşlu',
  'Fyodor Smolov',
  'Brais Méndez Portela',
  'Kevin Vázquez Comesaña',
  'Joseph Aidoo',
  'Néstor Alejandro Araújo Razo',
  'Rubén Blanco Veiga',
  'Manuel Agudo Durán',
  'Rafael Alcântara do Nascimento',
  'Filip Bradarić',
  'Jeison Fabián Murillo Cerón',
  'Santiago Mina Lorenzo',
  'Stanislav Lobotka',
  'Francisco José Beltrán Peinado',
  'Lucas René Olaza Catrofe',
  'David Juncà Reñé',
  'Pione Sisto Ifolo Emirmija',
  'Hugo Mallo Novegil',
  'Pape Cheikh Diop Gueye',
  'Gabriel Matías Fernández Leites'],
 'Real Valladolid': [nan,
  'Sergio Guardiola Navarro',
  'Rubén Alcaraz Jiménez',
  'Óscar Plano Pedreño',
  'Enrique Pérez Muñoz',
  'Joaquín Fernández Moreno',
  'Jordi Masip López',
  'Javier Moyano Lujano',
  'Francisco José Olivas Alba',
  'Federico San Emeterio Díaz',
  'Raúl García Carnero',
  'Javier Sánchez de Felipe',
  'José Ignacio Martínez García',
  'Pablo Hervías Ruiz',
  'Enes Ünal',
  'Sandro Ramírez Castillo',
  'Waldo Rubio Martín',
  'Miguel Alfonso Herrero Javaloyas',
  'Pedro Antonio Porro Sauceda',
  'Federico Barba',
  'Anuar Mohamed Tuhami',
  'Mohamed Salisu Abdul Karim'],
 'Leganés': [nan,
  'Miguel Ángel Guerrero Martín',
  'Roque Mesa Quevedo',
  'Javier Eraso Goñi',
  'Chidozie Collins Awaziem',
  'Aitor Ruibal García',
  'Rubén Salvador Pérez Del Mármol',
  'Jonathan Cristian Silva',
  'José Luis García del Pozo',
  'Iván Cuéllar Sacristán',
  'Unai Bustinza Martínez',
  'Rodrigo Tarín Higón',
  'Roger Claver Assalé Djapone',
  'Ibrahim Amadou',
  'Guido Marcelo Carrillo',
  'Kévin Manuel Rodrigues',
  'Bryan Gil Salvatierra',
  'Óscar Rodríguez Arnaiz',
  'Dimitrios Siovas',
  'Youssef En-Nesyri',
  'Roberto José Rosales Altuve',
  'Kenneth Josiah Omeruo',
  'Martin Braithwaite Christensen'],
 'Valencia': [nan,
  'Maximiliano Gómez González',
  'Ferrán Torres García',
  'Kevin Gameiro',
  'Daniel Wass',
  'Ezequiel Marcelo Garay',
  'Gabriel Armando de Abreu',
  'Francis Coquelin',
  'Carlos Soler Barragán',
  'Jaume Doménech Sánchez',
  'Geoffrey Kondogbia',
  'José Luis Gayá Peña',
  'Rodrigo Moreno Machado',
  'Jaume Vicent Costa Jordá',
  'Rubén Sobrino Pozuelo'],
 'Osasuna': [nan,
  'José Manuel Arnáiz Díaz',
  'David García Zubiría',
  'Raúl Rodríguez Navas',
  'Aridane Hernández Umpiérrez',
  'Adrián López Álvarez',
  'Jon Moncayola Tollar',
  'Pervis Josué Estupiñán Tenorio',
  'Darko Brašanac',
  'Iñigo Pérez Soto',
  'Sergio Herrera Pirón',
  'Ignacio Vidal Miralles',
  'Oier Sanjurjo Mate',
  'Enric Gallego Puigsech',
  'Enrique Barja Afonso',
  'Roberto Torres Morales',
  'Antonio Latorre Grueso'],
 'Real Sociedad': [nan,
  'Alexander Isak',
  'Martin Ødegaard',
  'Ander Barrenetxea Muguruza',
  'Ignacio Monreal Eraso',
  'Robin Aime Robert Le Normand',
  'Alejandro Remiro Gargallo',
  'Ander Guevara Lajo',
  'Cristian Portugués Manzanera',
  'Diego Javier Llorente Ríos',
  'Mikel Merino Zazón',
  'Andoni Gorosabel Espinosa',
  'Mikel Oyarzabal Ugarte',
  'Igor Zubeldía Elorza',
  'Willian José da Silva',
  'Joseba Zaldúa Bengoetxea',
  'Adnan Januzaj'],
 'Espanyol': [nan,
  'Raúl de Tomás Gómez',
  'David López Silva',
  'Pol Lozano Vizuete',
  'Víctor Gómez Perea',
  'Adrián Embarba Blázquez',
  'Leandro Daniel Cabrera Sasía',
  'Dídac Vilá Rosselló',
  'Bernardo José Espinosa Zúñiga',
  'Diego López Rodríguez',
  'Marc Roca Junqué',
  'Fernando Calero Villa',
  'Víctor Sánchez Mata',
  'Sergi Darder Moll',
  'Víctor Campuzano Bonilla',
  'Lei Wu',
  'Jonathan Calleri',
  'Javier López Rodríguez',
  'Óscar Melendo Jiménez',
  'Edinaldo Gomes Pereira',
  'Matías Ezequiel Vargas Martín',
  'Ander Iturraspe Derteano'],
 'Atlético Madrid': [nan,
  'Diego da Silva Costa',
  'José María Giménez de Vargas',
  'Felipe Augusto de Almeida Monteiro',
  'Renan Augusto Lodi dos Santos',
  'Jan Oblak',
  'Saúl Ñíguez Esclapez',
  'Yannick Ferreira Carrasco',
  'Marcos Llorente Moreno',
  'Santiago Arias Naranjo',
  'Thomas Teye Partey',
  'Ángel Martín Correa',
  'João Félix Sequeira',
  'Álvaro Borja Morata Martín',
  'Thomas Lemar',
  'Víctor Machín Pérez',
  'Héctor Miguel Herrera López',
  'Jorge Resurrección Merodio',
  'Mario Hermoso Canseco',
  'Kieran Trippier'],
 'Real Madrid': [nan,
  'Karim Benzema',
  'Carlos Henrique Casimiro',
  'Toni Kroos',
  'Francisco Román Alarcón Suárez',
  'Sergio Ramos García',
  'Raphaël Varane',
  'Daniel Carvajal Ramos',
  'Gareth Frank Bale',
  'Federico Santiago Valverde Dipetta',
  'Ferland Mendy',
  'Thibaut Courtois',
  'Luka Modrić',
  'Rodrygo Silva de Goes',
  'Marcelo Vieira da Silva Júnior',
  'Vinícius José Paixão de Oliveira Júnior',
  'Lucas Vázquez Iglesias',
  'Mariano Díaz Mejía'],
 'Mallorca': [nan,
  'Marc Pedraza Sarto',
  'Takefusa Kubo',
  'Joan Sastre Vanrell',
  'Manuel Reina Rodríguez',
  'Ante Budimir',
  'Martin Valjent',
  'Antonio José Raillo Arenas',
  'Alejandro Pozo Pozo',
  'Salvador Sevilla López',
  'Daniel José Rodríguez Vázquez',
  'Juan Camilo Hernández Suárez',
  'Júnior Wakalibille Lago',
  'Francisco Gámez López',
  'Iddrisu Baba Mohammed',
  'Yannis Salibur',
  'Abdón Prats Bastidas',
  'Aleix Febas Pérez',
  'Josep Señé Escudero'],
 'Sevilla': [nan,
  'Luuk de Jong',
  'Fernando Francisco Reges',
  'Éver Maximiliano David Banega',
  'Diego Carlos Santos Silva',
  'Daniel Filipe Martins Carriço',
  'Sergio Reguilón Rodríguez',
  'Manuel Agudo Durán',
  'Lucas Ariel Ocampos',
  'Óliver Torres Muñoz',
  'Jesús Navas González',
  'Tomáš Vaclík',
  'Munir El Haddadi Mohamed',
  'Joan Jordán Moreno',
  'Javier Hernández Balcázar',
  'Jules Koundé',
  'Jesús Joaquín Fernández Sáez de la Torre',
  'Youssef En-Nesyri',
  'Nemanja Gudelj',
  'Franco Damián Vázquez'],
 'Granada': [nan,
  'Ramon Olamilekan Azeez',
  'Álvaro Vadillo Cifuentes',
  'Carlos Fernández Luna',
  'Dimitri Foulquier',
  'Germán Sánchez Barahona',
  'Rui Tiago Dantas da Silva',
  'Darwin Daniel Machís Marcano',
  'Yan Brice Eteki',
  'Maxime Gonalons',
  'Víctor David Díaz Miguel',
  'Domingos Sousa Coutinho Meneses Duarte',
  'Yangel Clemente Herrera Ravelo',
  'José Antonio Rodríguez Díaz',
  'José Antonio Martínez Gil',
  'Roberto Soldado Rillo',
  'Ángel Montoro Sánchez',
  'Carlos Neva Tey'],
 'Villarreal': [nan,
  'Santiago Cazorla González',
  'Pau Francisco Torres',
  'Gerard Moreno Balaguero',
  'Vicente Iborra De La Fuente',
  'Rubén Peña Jiménez',
  'André-Frank Zambo Anguissa',
  'Xavier Quintillà Guasch',
  'Javier Ontiveros Parra',
  'Samuel Chimerenka Chukwueze',
  'Raúl Albiol Tortajada',
  'Sergio Asenjo Andrés',
  'Karl Brillant Toko Ekambi',
  'Moisés Gómez Bordonado',
  'Carlos Arturo Bacca Ahumada',
  'Alberto Moreno Pérez',
  'Mario Gaspar Pérez Martínez',
  'Francisco Alcácer García',
  'Bruno Soriano Llido',
  'Manuel Trigueros Muñoz',
  'Fernando Niño Rodriguez'],
 'Eibar': [nan,
  'Sergio Enrich Ametller',
  'Pedro León Sánchez Gil',
  'Fabián Ariel Orellana Valenzuela',
  'Paulo André Rodrigues de Oliveira',
  'Marko Dmitrović',
  'Anaitz Arbilla Zabala',
  'Sergio Álvarez Díaz',
  'José Ángel Valdés Díaz',
  'Pablo Ezequiel De Blasis',
  'Charles Días Barbosa de Oliveira',
  'Papa Kouly Diop',
  'Eduardo Expósito Jaén',
  'Takashi Inui',
  'Enrique García Martínez',
  'Gonzalo Escalante',
  'Álvaro Tejero Sacristán',
  'Esteban Rodrigo Burgos',
  'Enrique González Casín',
  'Sebastián Carlos Cristóforo Pepe'],
 'Real Betis': [nan,
  'Carles Aleña Castillo',
  'Borja Iglesias Quintas',
  'William Silva de Carvalho',
  'Marc Bartra Aregall',
  'Sergio Canales Madrazo',
  'Aïssa Mandi',
  'Joel Robles Blázquez',
  'Emerson Aparecido Leite de Souza Junior',
  'Guido Rodríguez',
  'Nabil Fekir',
  'Alejandro Moreno Lopera',
  'Lorenzo Jesús Morón García',
  'Joaquín Sánchez Rodríguez',
  'Cristian Tello Herrera'],
 'Levante': [nan,
  'Enis Bardhi',
  'Nemanja Radoja',
  'Jorge Miramón Santagertrudis',
  'José Ángel Gómez Campaña',
  'Borja Mayoral Moya',
  'Gonzalo Julián Melero Manzanares',
  'Rúben Miguel Nunes Vezo',
  'José Luis Morales Nogales',
  'Carlos Clerc Martínez',
  'Aitor Fernández Abarisketa',
  'Sergio Postigo Redondo',
  'Rubén Rochina Naixes',
  'Nikola Vukčević',
  'Erick Cathriel Cabaco Almada',
  'Roger Martí Salvador',
  'Antonio García Aranda',
  'Hernâni Jorge Santos Fortes'],
 'Getafe': [nan,
  'Marc Cucurella Saseta',
  'Jorge Molina Vidal',
  'Djené Dakonam Ortega',
  'Mauro Wilney Arambarri Rosa',
  'Xabier Etxeita Gorritxategi',
  'Nemanja Maksimović',
  'Mathías Olivera Miramontes',
  'Allan Romeo Nyom',
  'Oghenekaro Etebo',
  'Jaime Mata Arnaiz',
  'David Soria Solís',
  'Robert Kenedy Nunes do Nascimento',
  'Ángel Luis Rodríguez Díaz',
  'Amath Ndiaye']}

In [147]:
dd.head()

,match_id,possession,player.name,shot.statsbomb_xg,shot.outcome.id
0,303377,1,"[nan, nan, nan, nan]",0.0,0
1,303377,2,"[Antoine Griezmann, Sergio Busquets i Burgos, ...",0.0,0
2,303377,3,"[Xabier Etxeita Gorritxategi, Allan Romeo Nyom...",0.0,0
3,303377,4,"[Allan Romeo Nyom, Oghenekaro Etebo, Oghenekar...",0.0,0
4,303377,5,"[Samuel Yves Umtiti, Sergio Busquets i Burgos,...",0.0,0

In [128]:
matchids = df.match_id.unique()
for i in match_ids:
    match = df[df["match_id"] == i]
    goal_poss = match[match['shot.outcome.id']==97]["possession"].values
    scoring_team = match[match['shot.outcome.id']==97]["team.name"].values

In [80]:
dd[["shot.outcome.id","shot.outcome.name"]].value_counts()

shot.outcome.id  shot.outcome.name
98.0             Off T                8
100.0            Saved                6
96.0             Blocked              5
97.0             Goal                 2
101.0            Wayward              1
dtype: int64

In [81]:
dd[dd['shot.outcome.id']==97].minute

82734    70
83502    91
Name: minute, dtype: int64

In [82]:
dd[dd['shot.outcome.id']==97]["team.name"]

82734    Real Madrid
83502    Real Madrid
Name: team.name, dtype: object

In [83]:
dd[dd['shot.outcome.id']==97][["possession","match_id"]]

       possession  match_id
82734         165    303470
83502         198    303470

In [55]:
dd[dd['minute']==70]["player.name"]

82698                      Daniel Carvajal Ramos
82699                      Daniel Carvajal Ramos
82700                                        NaN
82701                      Daniel Carvajal Ramos
82702                   Carlos Henrique Casimiro
82703                   Carlos Henrique Casimiro
82704                      Daniel Carvajal Ramos
82705                      Daniel Carvajal Ramos
82706                      Daniel Carvajal Ramos
82707                              Karim Benzema
82708                           Jordi Alba Ramos
82709                              Karim Benzema
82710             Francisco Román Alarcón Suárez
82711             Francisco Román Alarcón Suárez
82712             Francisco Román Alarcón Suárez
82713                              Karim Benzema
82714                              Karim Benzema
82715                            Frenkie de Jong
82716                              Karim Benzema
82717             Francisco Román Alarcón Suárez
82718             Francisco Román Alarcón Suárez
82719             Francisco Román Alarcón Suárez
82720    Vinícius José Paixão de Oliveira Júnior
82721    Vinícius José Paixão de Oliveira Júnior
82722    Vinícius José Paixão de Oliveira Júnior
82723                              Karim Benzema
82724                              Karim Benzema
82725                              Karim Benzema
82726    Vinícius José Paixão de Oliveira Júnior
82727    Vinícius José Paixão de Oliveira Júnior
82728                                 Toni Kroos
82729                                 Toni Kroos
82730                                 Toni Kroos
82731    Vinícius José Paixão de Oliveira Júnior
82732    Vinícius José Paixão de Oliveira Júnior
82733                      Gerard Piqué Bernabéu
82734    Vinícius José Paixão de Oliveira Júnior
82735                      Gerard Piqué Bernabéu
82736                      Marc-André ter Stegen
Name: player.name, dtype: object